### ISSUE TITLE
How do you come to know about react-secure-storage ?

### ISSUE THREAD

**Issue by sushinpv** [javafadu/ReactLibraryApp#1]
Hi,
Could you please explain how you heard about React Secure Storage and how your experience has been so far?

**Comment by javafadu** [comment]
Hello, I heard it when i was at the bootcamp about Full-Stack development.
I use it generally so far if i need to keep bearer token at local storage.
Actually i do not know so much details this plugin but i am usigin it
mostly.

Thanks and Regards.

**Comment by sushinpv** [comment]
Thank you for your reply,
